force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Used to capture log information</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Request_Headers__c.field-meta.xml
<CustomField>
    <fullName>Request_Headers__c</fullName>
    <label>Request Headers</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Request_Url__c.field-meta.xml
<CustomField>
    <fullName>Request_Url__c</fullName>
    <label>Request Url</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Response_Headers__c.field-meta.xml
<CustomField>
    <fullName>Response_Headers__c</fullName>
    <label>Response Headers</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Response_Url__c.field-meta.xml
<CustomField>
    <fullName>Response_Url__c</fullName>
    <label>Response Url</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Logger.cls
/**
 * logging class for logging TODO: update this 
 */
public with sharing virtual class Logger {
    
    public String className { get; set; }
    public String methodName { get; set; }
    public String details { get; set; }
    public Datetime endTime { get; set; }
    public Logger.EventType eventType { get; set; }
    public String lineNumber { get; set; }
    public String requestBody { get; set; }
    public String requestHeaders { get; set; }
    public String requestUrl { get; set; }
    public String responseBody { get; set; }
    public String responseHeaders { get; set; }
    public String responseUrl { get; set; }
    public String stackTrace { get; set; }
    public Datetime startTime { get; set; }
    public Logger.Type type { get; set; }

    public enum EventType {
        ERROR,
        INFO,
        WARRING
    }

    public enum Type {
        APEX,
        BATCH,
        HTTP,
        LWC
    }
    
    public Logger() {
        this.details = '';
        this.startTime = System.now();
    }

    public Log__c end() {
        this.endTime = System.now();
        return this.saveLogger();
    }

    public void writeToDetails(String pText, String pObject) {
        this.details += pText + '\n' + pObject + '\n\n';
    }

    public Log__c saveLogger() {
        Log__c log = new Log__c(
            Class_Name__c = this.className,
            Method_Name__c = this.methodName,
            Details__c = this.details,
            End_Time__c = this.endTime,
            Event_Type__c = (this.eventType != null) ? this.eventType.name() : Logger.EventType.INFO.name(),
            Line_Number__c = lineNumber,
            Request_Body__c = this.requestBody,
            Request_Headers__c = this.requestHeaders,
            Request_Url__c = this.requestUrl,
            Response_Body__c = this.responseBody,
            Response_Headers__c = this.responseHeaders,
            Response_Url__c = this.responseUrl,
            Stack_Trace__c = this.stackTrace,
            Start_Time__c = this.startTime,
            Type__c = this.type.name()
        );

        return log;
    }

    /**
     * @description pass the string version of the object into the future!
     * @param {String} pJsonLog the json version of this object
     * @return void
     */
    @future
    public static void saveInTheFuture(String pJsonLog) {
        try {
            Logger log = (Logger)JSON.deserialize(pJsonLog, Logger.class);
            insert log.end();
        } catch(Exception e) {
            System.debug('Logger.saveInTheFuture ' + e.getMessage());
        }
    }
}